//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/authz/v1beta1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Cosmos_Authz_V1beta1_QueryClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Authz_V1beta1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Authz_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func authorization(
    _ request: Cosmos_Authz_V1beta1_QueryAuthorizationRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Authz_V1beta1_QueryAuthorizationRequest, Cosmos_Authz_V1beta1_QueryAuthorizationResponse>

  func authorizations(
    _ request: Cosmos_Authz_V1beta1_QueryAuthorizationsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Authz_V1beta1_QueryAuthorizationsRequest, Cosmos_Authz_V1beta1_QueryAuthorizationsResponse>
}

extension Cosmos_Authz_V1beta1_QueryClientProtocol {
  public var serviceName: String {
    return "cosmos.authz.v1beta1.Query"
  }

  /// Returns any `Authorization` (or `nil`), with the expiration time, granted to the grantee by the granter for the
  /// provided msg type.
  ///
  /// - Parameters:
  ///   - request: Request to send to Authorization.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func authorization(
    _ request: Cosmos_Authz_V1beta1_QueryAuthorizationRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Authz_V1beta1_QueryAuthorizationRequest, Cosmos_Authz_V1beta1_QueryAuthorizationResponse> {
    return self.makeUnaryCall(
      path: "/cosmos.authz.v1beta1.Query/Authorization",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAuthorizationInterceptors() ?? []
    )
  }

  /// Returns list of `Authorization`, granted to the grantee by the granter.
  ///
  /// - Parameters:
  ///   - request: Request to send to Authorizations.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func authorizations(
    _ request: Cosmos_Authz_V1beta1_QueryAuthorizationsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Authz_V1beta1_QueryAuthorizationsRequest, Cosmos_Authz_V1beta1_QueryAuthorizationsResponse> {
    return self.makeUnaryCall(
      path: "/cosmos.authz.v1beta1.Query/Authorizations",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAuthorizationsInterceptors() ?? []
    )
  }
}

public protocol Cosmos_Authz_V1beta1_QueryClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'authorization'.
  func makeAuthorizationInterceptors() -> [ClientInterceptor<Cosmos_Authz_V1beta1_QueryAuthorizationRequest, Cosmos_Authz_V1beta1_QueryAuthorizationResponse>]

  /// - Returns: Interceptors to use when invoking 'authorizations'.
  func makeAuthorizationsInterceptors() -> [ClientInterceptor<Cosmos_Authz_V1beta1_QueryAuthorizationsRequest, Cosmos_Authz_V1beta1_QueryAuthorizationsResponse>]
}

public final class Cosmos_Authz_V1beta1_QueryClient: Cosmos_Authz_V1beta1_QueryClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Authz_V1beta1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.authz.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Authz_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Cosmos_Authz_V1beta1_QueryProvider: CallHandlerProvider {
  var interceptors: Cosmos_Authz_V1beta1_QueryServerInterceptorFactoryProtocol? { get }

  /// Returns any `Authorization` (or `nil`), with the expiration time, granted to the grantee by the granter for the
  /// provided msg type.
  func authorization(request: Cosmos_Authz_V1beta1_QueryAuthorizationRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Cosmos_Authz_V1beta1_QueryAuthorizationResponse>

  /// Returns list of `Authorization`, granted to the grantee by the granter.
  func authorizations(request: Cosmos_Authz_V1beta1_QueryAuthorizationsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Cosmos_Authz_V1beta1_QueryAuthorizationsResponse>
}

extension Cosmos_Authz_V1beta1_QueryProvider {
  public var serviceName: Substring { return "cosmos.authz.v1beta1.Query" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Authorization":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cosmos_Authz_V1beta1_QueryAuthorizationRequest>(),
        responseSerializer: ProtobufSerializer<Cosmos_Authz_V1beta1_QueryAuthorizationResponse>(),
        interceptors: self.interceptors?.makeAuthorizationInterceptors() ?? [],
        userFunction: self.authorization(request:context:)
      )

    case "Authorizations":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cosmos_Authz_V1beta1_QueryAuthorizationsRequest>(),
        responseSerializer: ProtobufSerializer<Cosmos_Authz_V1beta1_QueryAuthorizationsResponse>(),
        interceptors: self.interceptors?.makeAuthorizationsInterceptors() ?? [],
        userFunction: self.authorizations(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Cosmos_Authz_V1beta1_QueryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'authorization'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAuthorizationInterceptors() -> [ServerInterceptor<Cosmos_Authz_V1beta1_QueryAuthorizationRequest, Cosmos_Authz_V1beta1_QueryAuthorizationResponse>]

  /// - Returns: Interceptors to use when handling 'authorizations'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAuthorizationsInterceptors() -> [ServerInterceptor<Cosmos_Authz_V1beta1_QueryAuthorizationsRequest, Cosmos_Authz_V1beta1_QueryAuthorizationsResponse>]
}
