//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/feegrant/v1beta1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Msg defines the feegrant msg service.
///
/// Usage: instantiate `Cosmos_Feegrant_V1beta1_MsgClient`, then call methods of this protocol to make API calls.
public protocol Cosmos_Feegrant_V1beta1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmos_Feegrant_V1beta1_MsgClientInterceptorFactoryProtocol? { get }

  func grantFeeAllowance(
    _ request: Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance, Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowanceResponse>

  func revokeFeeAllowance(
    _ request: Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance, Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowanceResponse>
}

extension Cosmos_Feegrant_V1beta1_MsgClientProtocol {
  public var serviceName: String {
    return "cosmos.feegrant.v1beta1.Msg"
  }

  /// GrantFeeAllowance grants fee allowance to the grantee on the granter's
  /// account with the provided expiration time.
  ///
  /// - Parameters:
  ///   - request: Request to send to GrantFeeAllowance.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func grantFeeAllowance(
    _ request: Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance, Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowanceResponse> {
    return self.makeUnaryCall(
      path: "/cosmos.feegrant.v1beta1.Msg/GrantFeeAllowance",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGrantFeeAllowanceInterceptors() ?? []
    )
  }

  /// RevokeFeeAllowance revokes any fee allowance of granter's account that
  /// has been granted to the grantee.
  ///
  /// - Parameters:
  ///   - request: Request to send to RevokeFeeAllowance.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func revokeFeeAllowance(
    _ request: Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance, Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowanceResponse> {
    return self.makeUnaryCall(
      path: "/cosmos.feegrant.v1beta1.Msg/RevokeFeeAllowance",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRevokeFeeAllowanceInterceptors() ?? []
    )
  }
}

public protocol Cosmos_Feegrant_V1beta1_MsgClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'grantFeeAllowance'.
  func makeGrantFeeAllowanceInterceptors() -> [ClientInterceptor<Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance, Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowanceResponse>]

  /// - Returns: Interceptors to use when invoking 'revokeFeeAllowance'.
  func makeRevokeFeeAllowanceInterceptors() -> [ClientInterceptor<Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance, Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowanceResponse>]
}

public final class Cosmos_Feegrant_V1beta1_MsgClient: Cosmos_Feegrant_V1beta1_MsgClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Cosmos_Feegrant_V1beta1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmos.feegrant.v1beta1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmos_Feegrant_V1beta1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Msg defines the feegrant msg service.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Cosmos_Feegrant_V1beta1_MsgProvider: CallHandlerProvider {
  var interceptors: Cosmos_Feegrant_V1beta1_MsgServerInterceptorFactoryProtocol? { get }

  /// GrantFeeAllowance grants fee allowance to the grantee on the granter's
  /// account with the provided expiration time.
  func grantFeeAllowance(request: Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance, context: StatusOnlyCallContext) -> EventLoopFuture<Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowanceResponse>

  /// RevokeFeeAllowance revokes any fee allowance of granter's account that
  /// has been granted to the grantee.
  func revokeFeeAllowance(request: Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance, context: StatusOnlyCallContext) -> EventLoopFuture<Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowanceResponse>
}

extension Cosmos_Feegrant_V1beta1_MsgProvider {
  public var serviceName: Substring { return "cosmos.feegrant.v1beta1.Msg" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GrantFeeAllowance":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance>(),
        responseSerializer: ProtobufSerializer<Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowanceResponse>(),
        interceptors: self.interceptors?.makeGrantFeeAllowanceInterceptors() ?? [],
        userFunction: self.grantFeeAllowance(request:context:)
      )

    case "RevokeFeeAllowance":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance>(),
        responseSerializer: ProtobufSerializer<Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowanceResponse>(),
        interceptors: self.interceptors?.makeRevokeFeeAllowanceInterceptors() ?? [],
        userFunction: self.revokeFeeAllowance(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Cosmos_Feegrant_V1beta1_MsgServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'grantFeeAllowance'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGrantFeeAllowanceInterceptors() -> [ServerInterceptor<Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowance, Cosmos_Feegrant_V1beta1_MsgGrantFeeAllowanceResponse>]

  /// - Returns: Interceptors to use when handling 'revokeFeeAllowance'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRevokeFeeAllowanceInterceptors() -> [ServerInterceptor<Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowance, Cosmos_Feegrant_V1beta1_MsgRevokeFeeAllowanceResponse>]
}
